/* eslint-disable camelcase */
const mappings = {
  ConfigurationAttribute__c: 'MigrationAttribute',
  ConfigurationCategory__c: 'MigrationCategory',
  ConfigurationGroup__c: 'MigrationGroup',
  ConfigurationKey__c: 'MigrationKey',
  ConfigurationPattern__c: 'MigrationPattern',
  ConfigurationProcess__c: 'MigrationProcess',
  ConfigurationType__c: 'MigrationType',
  ConfigurationValue__c: 'MigrationValue',
  DefaultValue__c: 'DefaultValue',
  DisplayType__c: 'FilterDataType',
  DomainObjectAPIName__c: 'OutputObjectName',
  DomainObjectCreationOrder__c: 'OutputCreationSequence',
  DomainObjectFieldAPIName__c: 'OutputFieldName',
  DomainObjectFieldType__c: 'OutputFieldFormat',
  FilterGroup__c: 'FilterGroup',
  FilterOperator__c: 'FilterOperator',
  FilterValue__c: 'FilterValue',
  Formula__c: 'FormulaExpression',
  FormulaConverted__c: 'FormulaConverted',
  FormulaOrder__c: 'FormulaSequence',
  FormulaResultPath__c: 'FormulaResultPath',
  InterfaceFieldAPIName__c: 'InputFieldName',
  InterfaceObjectLookupOrder__c: 'InputObjectQuerySequence',
  InterfaceObjectName__c: 'InputObjectName',
  IsDisabled__c: 'IsDisabled',
  IsRequiredForUpsert__c: 'IsRequiredForUpsert',
  LinkCreatedField__c: 'LinkedFieldName',
  LinkCreatedIndex__c: 'LinkedObjectSequence',
  LookupDomainObjectFieldName__c: 'LookupByFieldName',
  LookupDomainObjectName__c: 'LookupObjectName',
  LookupDomainObjectRequestedFieldName__c: 'LookupReturnedFieldName',
  MapId__c: 'GlobalKey',
  Name: 'Name',
  TransformValuesMap__c: 'TransformValueMappings',
  UpsertKey__c: 'IsUpsertKey',
  GlobalKey__c: 'GlobalKey',
};

export default mappings;
