// OmniProcess.ts

const OmniProcessMappings = {
  CreatedById: 'CreatedById',
  CreatedDate: 'CreatedDate',
  CustomHtmlTemplates: 'CustomHtmlTemplates__c',
  CustomJavaScript: 'CustomJavaScript__c',
  Description: 'Description',
  DesignerCustomizationType: 'DesignerCustomizationType__c',
  ElementTypeComponentMapping: 'ElementTypeComponentMapping__c',
  Id: 'Id',
  IsActive: 'IsActive',
  IsDeleted: 'IsDeleted',
  IsIntegrationProcedure: 'IsIntegrationProcedure__c',
  IsMetadataCacheDisabled: 'IsMetadataCacheDisabled__c',
  IsOmniScriptEmbeddable: 'IsOmniScriptEmbeddable__c',
  IsTestProcedure: 'IsTestProcedure__c',
  IsWebCompEnabled: 'IsWebCompEnabled__c',
  Language: 'Language',
  LastModifiedById: 'LastModifiedById',
  LastModifiedDate: 'LastModifiedDate',
  LastPreviewPage: 'LastPreviewPage__c',
  LastReferencedDate: 'LastReferencedDate',
  LastViewedDate: 'LastViewedDate',
  Name: 'Name',
  Namespace: 'NamespacePrefix',
  OmniProcessKey: 'OmniProcessKey__c',
  OmniProcessType: 'OmniProcessType__c',
  OverrideKey: 'OverrideKey__c',
  OwnerId: 'OwnerId',
  PropertySetConfig: 'PropertySetConfig__c',
  RequiredPermission: 'RequiredPermission__c',
  ResponseCacheType: 'ResponseCacheType__c',
  SubType: 'SubType__c',
  SystemModstamp: 'SystemModstamp',
  Type: 'Type__c',
  UniqueName: 'UniqueName__c',
  VersionNumber: 'VersionNumber__c',
  WebComponentKey: 'WebComponentKey__c',
};

export default OmniProcessMappings;
